# Generated by Django 5.2.4 on 2025-08-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='can_retake',
            field=models.BooleanField(default=False, verbose_name='Qayta topshirishga ruxsat (controller)'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester', verbose_name='Semestr'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Fan'),
        ),
        migrations.AddConstraint(
            model_name='studenttest',
            constraint=models.UniqueConstraint(condition=models.Q(('can_retake', False), ('completed', True)), fields=('student', 'group', 'subject', 'semester'), name='unique_student_group_subject_semester_once'),
        ),
    ]
