# Generated by Django 5.2.4 on 2025-09-03 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studenttest_can_retake_studenttest_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'zgartirilgan vaqt"),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_tests', to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi"),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='overridden_score',
            field=models.FloatField(blank=True, null=True, verbose_name="Qo'lda o'zgartirilgan ball"),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='override_reason',
            field=models.TextField(blank=True, null=True, verbose_name="O'zgartirish sababi"),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='pass_override',
            field=models.BooleanField(default=False, verbose_name="Majburan o'tkazish (override)"),
        ),
        migrations.CreateModel(
            name='StudentTestModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_score', models.FloatField(blank=True, null=True, verbose_name='Oldingi ball')),
                ('new_score', models.FloatField(blank=True, null=True, verbose_name='Yangi ball')),
                ('previous_pass_override', models.BooleanField(default=False, verbose_name="Oldingi majburiy o'tkazish")),
                ('new_pass_override', models.BooleanField(default=False, verbose_name="Yangi majburiy o'tkazish")),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('change_type', models.CharField(choices=[('override', 'Override'), ('revert', 'Revert')], max_length=20, verbose_name="O'zgarish turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_changes', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan foydalanuvchi")),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='main.studenttest', verbose_name='Talaba testi')),
            ],
            options={
                'verbose_name': "Natija o'zgarishi",
                'verbose_name_plural': "Natija o'zgarishlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
